### ISSUE TITLE
对谷歌香港的域名不起作用

### ISSUE THREAD

**Issue by lainbo** [zhengbangbo/chat-gpt-userscript#6]
**Describe the bug**
在谷歌香港的域名中不起作用

**To Reproduce**
1. 打开'https://www.google.com.hk/search?q=xxx'

**Expected behavior**
期望在右侧能看见Chat GPT的对话框

**Comment by zhengbangbo** [comment]
谢谢，已确认
________________________________
发件人: lainbo ***@***.***>
发送时间: 2022年12月8日 11:59
收件人: zhengbangbo/chat-gpt-userscript ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zhengbangbo/chat-gpt-userscript] 对谷歌香港的域名不起作用 (Issue #6)


Describe the bug
在谷歌香港的域名中不起作用

To Reproduce
Steps to reproduce the behavior:

  1.  打开'https://www.google.com.hk/search?q=xxx<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.hk%2Fsearch%3Fq%3Dxxx&data=05%7C01%7C%7Ce489f633e1774d610ead08dad8d09396%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638060687592826441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qIR0QbWbAI56v6wv8YBH39%2F7jE%2Far2itGbFmTOJ2Blo%3D&reserved=0>'

Expected behavior
期望在右侧能看见Chat GPT的对话框

―

**Comment by zhengbangbo** [comment]
[v0.3.3](https://greasyfork.org/scripts/456077-chat-gpt-search-sidebar/code?version=1126055) 已修复这个问题

**Comment by zhengbangbo** [comment]
刚发现语法不符合规范，在 Violentmonkey 中被兼容，但在 Tampermonkey 不受支持。已在 [v0.3.4](https://greasyfork.org/scripts/456077-chat-gpt-search-sidebar?version=1126087) 切换为合法语法。
